miniFOC: hardware/flash.h File Reference
flash.h File Reference
this is the header file of flash.c.
Functions
void flash_write_parameters (void)
program all parameters to flash
void flash_read_parameters (void)
read all parameters from flash
void flash_erase_page (void)
erase flash page in last sector
void flash_program_word (unsigned int addr, unsigned int *data, unsigned char counter)
program flash word to address
unsigned int flash_read_word (unsigned int addr)
read flash word from address
Detailed Description
this is the header file of flash.c.
Author
Lao·Zhu
Version
V1.0.1
Date
10. October 2021
Definition in file flash.h.
Function Documentation
flash_erase_page()
void flash_erase_page (void)
erase flash page in last sector
Definition at line 76 of file flash.c.
References FMC_WRITE_START_ADDR.
Referenced by flash_write_parameters().
flash_program_word()
void flash_program_word (unsigned int addr, unsigned int * data, unsigned char counter)
program flash word to address
Parameters
[in] addr address to write to
[in] data data to be written
[in] counter number of bytes to be written to flash
Definition at line 95 of file flash.c.
References FMC_WRITE_START_ADDR.
Referenced by flash_write_parameters().
flash_read_parameters()
void flash_read_parameters (void)
read all parameters from flash
Definition at line 46 of file flash.c.
References angle_pid_handler, flash_read_word(), foc_parameter_available_flag, int32_to_float(), JUDGE_AVAILABLE, PID_Structure_t::kd, PID_Structure_t::ki, PID_Structure_t::kp, machine_angle_offset, phase_sequence, pid_parameter_available_flag, speed_pid_handler, and PID_Structure_t::sum_maximum.
Referenced by main().
flash_read_word()
unsigned int flash_read_word (unsigned int addr)
read flash word from address
Parameters
[in] addr address to read from
Return values
data read from address
Definition at line 114 of file flash.c.
References FMC_WRITE_START_ADDR.
Referenced by flash_read_parameters().
flash_write_parameters()
void flash_write_parameters (void)
program all parameters to flash
Definition at line 26 of file flash.c.
References angle_pid_handler, flash_erase_page(), flash_program_word(), float_to_int32(), PID_Structure_t::kd, PID_Structure_t::ki, PID_Structure_t::kp, machine_angle_offset, phase_sequence, pid_parameter_available_flag, speed_pid_handler, and PID_Structure_t::sum_maximum.
Referenced by main().