miniFOC: system/gd32f1x0_it.h File Reference
gd32f1x0_it.h File Reference
gd32f1x0 interrupt handler function header file
#include "gd32f1x0.h"
Functions
void NMI_Handler (void)
this function handles NMI exception
void HardFault_Handler (void)
this function handles HardFault exception
void MemManage_Handler (void)
this function handles MemManage exception
void BusFault_Handler (void)
this function handles BusFault exception
void UsageFault_Handler (void)
this function handles UsageFault exception
void SVC_Handler (void)
this function handles SVC exception
void DebugMon_Handler (void)
this function handles DebugMon exception
void PendSV_Handler (void)
this function handles PendSV exception
void SysTick_Handler (void)
this function handles SysTick exception
void USART0_IRQHandler (void)
this function handles USART RBNE interrupt request
void TIMER2_IRQHandler (void)
this function handles TIMER2 TIMER_INT_UP interrupt request
void TIMER13_IRQHandler (void)
this function handles TIMER13 TIMER_INT_UP interrupt request
Detailed Description
gd32f1x0 interrupt handler function header file
Author
Lao·Zhu
Version
V1.0.1
Date
9. October 2021
Definition in file gd32f1x0_it.h.
Function Documentation
BusFault_Handler()
void BusFault_Handler (void)
this function handles BusFault exception
Definition at line 43 of file gd32f1x0_it.c.
DebugMon_Handler()
void DebugMon_Handler (void)
this function handles DebugMon exception
Definition at line 65 of file gd32f1x0_it.c.
HardFault_Handler()
void HardFault_Handler (void)
this function handles HardFault exception
Definition at line 27 of file gd32f1x0_it.c.
MemManage_Handler()
void MemManage_Handler (void)
this function handles MemManage exception
Definition at line 35 of file gd32f1x0_it.c.
NMI_Handler()
void NMI_Handler (void)
this function handles NMI exception
Definition at line 21 of file gd32f1x0_it.c.
PendSV_Handler()
void PendSV_Handler (void)
this function handles PendSV exception
Definition at line 71 of file gd32f1x0_it.c.
SVC_Handler()
void SVC_Handler (void)
this function handles SVC exception
Definition at line 59 of file gd32f1x0_it.c.
SysTick_Handler()
void SysTick_Handler (void)
this function handles SysTick exception
Definition at line 77 of file gd32f1x0_it.c.
References delay_decrement(), encoder_update_speed(), SPEED_UP_FREQ, and systick_counter.
TIMER13_IRQHandler()
void TIMER13_IRQHandler (void)
this function handles TIMER13 TIMER_INT_UP interrupt request
Definition at line 124 of file gd32f1x0_it.c.
References ANGLE_LOOP_CONTROL, angle_pid_handler, PID_Structure_t::expect, FOC_Struct, FOC_Structure_t::mechanical_angle, pid_calculate_result(), pid_control_mode_flag, FOC_Structure_t::rotate_speed, speed_pid_handler, and FOC_Structure_t::user_expect.
TIMER2_IRQHandler()
void TIMER2_IRQHandler (void)
this function handles TIMER2 TIMER_INT_UP interrupt request
Definition at line 104 of file gd32f1x0_it.c.
References encoder_get_electronic_angle(), foc_calculate_dutycycle(), FOC_Struct, phase_sequence, update_pwm_dutycycle(), and FOC_Structure_t::user_expect.
UsageFault_Handler()
void UsageFault_Handler (void)
this function handles UsageFault exception
Definition at line 51 of file gd32f1x0_it.c.
USART0_IRQHandler()
void USART0_IRQHandler (void)
this function handles USART RBNE interrupt request
Definition at line 92 of file gd32f1x0_it.c.
References mdtp_receive_handler().