miniFOC: algorithm/report.c File Reference
report.c File Reference
this file is used to write the report correlation function of the feedback host computer.
#include "main.h"
Functions
void report_local_variable (void)
report PID parameters and current user settings
void report_angle_speed (void)
report angle and speed using medium capacity transport protocol
Detailed Description
this file is used to write the report correlation function of the feedback host computer.
Author
Lao·Zhu
Version
V1.0.2
Date
29. October 2021
Definition in file report.c.
Function Documentation
report_angle_speed()
void report_angle_speed (void)
report angle and speed using medium capacity transport protocol
Definition at line 69 of file report.c.
References float_to_int32(), FOC_Struct, mdtp_data_transmit(), FOC_Structure_t::mechanical_angle, and FOC_Structure_t::rotate_speed.
Referenced by main().
report_local_variable()
void report_local_variable (void)
report PID parameters and current user settings
Definition at line 15 of file report.c.
References ANGLE_LOOP_CONTROL, angle_pid_handler, delayms(), PID_Structure_t::expect, float_to_int32(), foc_parameter_available_flag, FOC_Struct, PID_Structure_t::kd, PID_Structure_t::ki, PID_Structure_t::kp, led_toggle, machine_angle_offset, mdtp_data_transmit(), phase_sequence, pid_control_mode_flag, pid_parameter_available_flag, SPEED_LOOP_CONTROL, speed_pid_handler, PID_Structure_t::sum_maximum, TORQUE_LOOP_CONTROL, and FOC_Structure_t::user_expect.
Referenced by main().