miniFOC: hardware/timer.h File Reference
timer.h File Reference
this is the header file of timer.c.
Macros
#define PWM_PERIOD 18000 / PWM_FREQUENCY
PWM period calculate from PWM_FREQUENCY.
Functions
void update_pwm_dutycycle (float ch0, float ch1, float ch2)
update timer1 ch0 1 2 duty-cycle
void timer2_disable (void)
disable timer2 periph and timer2 interrupt
void timer13_disable (void)
disable timer13 periph and timer2 interrupt
void timer2_config (void)
configure timer2 periph for timing interrupt
void timer13_config (void)
configure timer13 periph for timing interrupt
void pwm_config (void)
configure timer1 periph and its gpios
Detailed Description
this is the header file of timer.c.
Author
Lao·Zhu
Version
V1.0.1
Date
10. October 2021
Definition in file timer.h.
Macro Definition Documentation
PWM_PERIOD
#define PWM_PERIOD 18000 / PWM_FREQUENCY
PWM period calculate from PWM_FREQUENCY.
Definition at line 15 of file timer.h.
Function Documentation
pwm_config()
void pwm_config (void)
configure timer1 periph and its gpios
Definition at line 117 of file timer.c.
References PWM_PERIOD.
Referenced by main().
timer13_config()
void timer13_config (void)
configure timer13 periph for timing interrupt
Definition at line 89 of file timer.c.
References TIM13_FREQUENCY, and TIM13_PRIORITY.
Referenced by main().
timer13_disable()
void timer13_disable (void)
disable timer13 periph and timer2 interrupt
Definition at line 30 of file timer.c.
Referenced by main().
timer2_config()
void timer2_config (void)
configure timer2 periph for timing interrupt
Definition at line 61 of file timer.c.
References TIM2_FREQUENCY, and TIM2_PRIORITY.
Referenced by main().
timer2_disable()
void timer2_disable (void)
disable timer2 periph and timer2 interrupt
Definition at line 44 of file timer.c.
References update_pwm_dutycycle().
Referenced by main().
update_pwm_dutycycle()
void update_pwm_dutycycle (float ch0, float ch1, float ch2)
update timer1 ch0 1 2 duty-cycle
Parameters
[in] ch0 duty-cycle of channel0, 0 ~ 1.0f
[in] ch1 duty-cycle of channel1, 0 ~ 1.0f
[in] ch2 duty-cycle of channel2, 0 ~ 1.0f
Definition at line 20 of file timer.c.
References PWM_PERIOD.
Referenced by encoder_zeroing(), foc_calibrate_phase(), timer2_disable(), and TIMER2_IRQHandler().