miniFOC: hardware/uart.c File Reference
uart.c File Reference
this file contains the code implementation of UART interface initialization function and medium capacity transmission protocol transceiver function.
#include "uart.h"
#include "config.h"
#include "gd32f1x0.h"
#include "system.h"
Functions
void mdtp_receive_handler (unsigned char data)
medium capacity data transmission protocol unpacking handler
void mdtp_data_transmit (unsigned char pid, const unsigned char *buffer)
medium capacity data transmission protocol packing function
void uart_config (void)
configure uart0 periph and its gpios
Variables
static volatile unsigned char mdtp_receive_status = 0
medium capacity transport protocol receive state variable 0 idle state and waiting for start of package
1 receive status trying to receive a complete packet.
2 end status processing the received data
static volatile unsigned char mdtp_receive_number_counter = 0
medium capacity transport protocol receive character counter
static unsigned char mdtp_receive_data_buffer [10] = {0}
medium capacity transport protocol receive buffer array
Detailed Description
this file contains the code implementation of UART interface initialization function and medium capacity transmission protocol transceiver function.
Author
Lao·Zhu
Version
V1.0.2
Date
29. October 2021
Definition in file uart.c.
Function Documentation
mdtp_data_transmit()
void mdtp_data_transmit (unsigned char pid, const unsigned char * buffer)
medium capacity data transmission protocol packing function
Parameters
[in] pid medium capacity transport protocol package id
[in] buffer transmit data array of size 8 bytes
Definition at line 113 of file uart.c.
References uart_sendbyte.
Referenced by report_angle_speed(), and report_local_variable().
mdtp_receive_handler()
void mdtp_receive_handler (unsigned char data)
medium capacity data transmission protocol unpacking handler
Parameters
[in] data data received from UART peripheral
Definition at line 36 of file uart.c.
References mdtp_callback_handler(), mdtp_receive_data_buffer, mdtp_receive_number_counter, mdtp_receive_status, and user_memset().
Referenced by USART0_IRQHandler().
uart_config()
void uart_config (void)
configure uart0 periph and its gpios
Definition at line 143 of file uart.c.
References UART_BAUDRATE, and UART_PRIORITY.
Referenced by main().
Variable Documentation
mdtp_receive_data_buffer
unsigned char mdtp_receive_data_buffer[10] = {0} static
medium capacity transport protocol receive buffer array
Definition at line 30 of file uart.c.
Referenced by mdtp_receive_handler().
mdtp_receive_number_counter
volatile unsigned char mdtp_receive_number_counter = 0 static
medium capacity transport protocol receive character counter
Definition at line 26 of file uart.c.
Referenced by mdtp_receive_handler().
mdtp_receive_status
volatile unsigned char mdtp_receive_status = 0 static
medium capacity transport protocol receive state variable 0 idle state and waiting for start of package
1 receive status trying to receive a complete packet.
2 end status processing the received data
Definition at line 22 of file uart.c.
Referenced by mdtp_receive_handler().