//
// Created by LaoZhu on 2023/6/27.
//

#ifndef MINIFOC_USER_CONFIG_H_
#define MINIFOC_USER_CONFIG_H_

#define TIM1_PRESCALER 1
#define PWM_FREQUENCY 20000

#define UART_RECEIVE_BUFFER_SIZE 256
#define UART_TRANSMIT_BUFFER_SIZE 32
#define UART_TRANSMIT_BUFFER_NUM 8

#endif  //MINIFOC_USER_CONFIG_H_
